name: Mirror FreeScout (latest) to CloudFlare Registry

on:
  workflow_dispatch: 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Internal Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_URL }}" \
            --username "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Pull upstream FreeScout image
        run: |
          docker pull ghcr.io/tiredofit/docker-freescout:php8.3-latest

      - name: Retag for internal registry
        run: |
          docker tag \
            ghcr.io/tiredofit/docker-freescout:php8.3-latest \
            ${{ secrets.REGISTRY_URL }}/freescout:latest

          docker tag \
            ghcr.io/tiredofit/docker-freescout:php8.3-latest \
            ${{ secrets.REGISTRY_URL }}/freescout:sha-${GITHUB_SHA}

      - name: Push to internal registry
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/freescout:latest
          docker push ${{ secrets.REGISTRY_URL }}/freescout:sha-${GITHUB_SHA}
